apiVersion: v1
kind: Pod
metadata:
  name: nfsvol
  labels:
    name: nfsvol
spec:
  volumes:
    - name: nfsvol
      nfs:
          # Use real NFS server address here.
          server: 198.18.11.3
          # Use real NFS server export directory.
          path: "/export/nfsvol"
          readOnly: false
  containers:
    - name: nfsvol
      image: singen/dockervol
      ports:
        - containerPort: 80
          name: "dockervol-httpd"
          protocol: TCP

      volumeMounts:
        # 'name' must match the volume name below.
        - name: nfsvol
          # Where to mount the volume.
          mountPath: "/mnt"
