apiVersion: v1
kind: Pod
metadata:
  name: dockervol
  labels:
    name: dockervol-persistent
spec:
  containers:
    - resources:
        limits :
          cpu: 2
          memory: 2048Mi
      image: singen/dockervol
      name: dockervol

      ports:
        - containerPort: 80
          name: "dockervol-httpd"

      volumeMounts:
        - mountPath: "/var/www/html"
          name: mypd

      volumes:
        - name: mypd

 persistentVolumeClaim:
     claimName: myclaim-1
