apiVersion: v1
kind: Service
metadata:
  labels:
    name: dockervol
  name: dockervol
spec:
  ports:
    # the port that this service should serve on
    - port: 80
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: dockervol
  type: NodePort
